# Generated by Django 4.0.4 on 2022-05-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('datebirth', models.DateField()),
                ('edad', models.IntegerField()),
                ('relathionship', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
